CREATE USER admin1 IDENTIFIED BY admin1;

CREATE USER shipper IDENTIFIED BY s1;

CREATE USER shipper1 IDENTIFIED BY 1;

CREATE USER customer IDENTIFIED BY c1;

CREATE USER staff IDENTIFIED BY staff1;

CREATE USER partner IDENTIFIED BY p1;

CREATE USER partner1 IDENTIFIED BY 1;


GRANT ALL PRIVILEGES TO admin1;


GRANT SELECT, INSERT, UPDATE, DELETE ON YUN.SANPHAM_CHINHANH TO partner;

GRANT SELECT, INSERT, UPDATE, DELETE ON YUN.SANPHAM TO partner;

GRANT SELECT, UPDATE (TINH_TRANG) ON YUN.CHITIETDONHANG TO partner;

GRANT SELECT, INSERT, UPDATE, DELETE ON YUN.SANPHAM_CHINHANH TO partner1;

GRANT SELECT, INSERT, UPDATE, DELETE ON YUN.SANPHAM TO partner1;

GRANT SELECT, UPDATE (TINH_TRANG) ON YUN.CHITIETDONHANG TO partne1;


GRANT SELECT ON YUN.HOPDONG TO staff;

GRANT SELECT ON YUN.TAIXEDH TO shipper;

GRANT SELECT ON YUN.TAIXEDH TO shipper1;


GRANT CREATE SESSION TO partner;

GRANT CREATE SESSION TO admin1;

GRANT CREATE SESSION TO staff;

GRANT CREATE SESSION TO partner1;

GRANT CREATE SESSION TO shipper;

GRANT CREATE SESSION TO customer;

GRANT CREATE SESSION TO shipper1



GRANT SELECT, UPDATE (ma_DH,tinh_trang,tien_do) on YUN.chitietdonhang to shipper;

GRANT SELECT, UPDATE (ma_DH,tinh_trang,tien_do) on YUN.chitietdonhang to shipper1;

GRANT INSERT ON YUN.SanPham to partner;

GRANT INSERT ON YUN.SanPham to partner1;

GRANT EXECUTE ON PARTNER_ADD_BRANCH TO PARTNER;

GRANT EXECUTE ON PARTNER_ADD_PRODUCT_TO_BRANCH TO PARTNER;

GRANT EXECUTE ON PARTNER_REMOVE_PRODUCT_FROM_BRANCH TO PARTNER;

GRANT EXECUTE ON PARTNER_GET_ORDERS TO PARTNER;

GRANT EXECUTE ON PARTNER_OR_DRIVER_UPDATE_DELIVERY_STATUS TO PARTNER;

GRANT EXECUTE ON PARTNER_UPDATE_PRODUCTS_DETAILS TO PARTNER;

GRANT EXECUTE ON PARTNER_REGISTATION TO PARTNER;

GRANT EXECUTE ON PARTNER_ADD_ORDER TO PARTNER;

GRANT EXECUTE ON PARTNER_ORDER_TRACKING TO PARTNER;

GRANT EXECUTE ON PARTNER_PRINT_ORDER TO PARTNER;

GRANT EXECUTE ON PARTNER_REMOVE_ORDER TO PARTNER;

GRANT EXECUTE ON PARTNER_PRINT_PRODUCTS_DETAILS TO PARTNER;

GRANT EXECUTE ON PARTNER_ADD_PRODUCT TO PARTNER;

GRANT EXECUTE ON PARTNER_REMOVE_PRODUCT TO PARTNER;

GRANT SELECT, UPDATE ON YUN.DONHANG TO PARTNER;




GRANT SELECT ON YUN.CHITIETDONHANG TO customer;

GRANT SELECT ON YUN.donHang to customer;

GRANT EXECUTE ON CUSTOMER_REGISTRATION TO CUSTOMER;

GRANT EXECUTE ON CUSTOMER_ADD_PRODUCT_TO_ORDER TO CUSTOMER;

GRANT EXECUTE ON CUSTOMER_UPDATE_PRODUCT_TO_ORDER TO CUSTOMER;

GRANT SELECT ON YUN.KHACHHANG TO customer;

GRANT SELECT, UPDATE (DIA_CHI_KH, SDT_KH)ON YUN.KHACHHANG TO customer;


GRANT EXECUTE ON DRIVER_GET_ORDERS TO SHIPPER;

GRANT EXECUTE ON DRIVER_RECEIVE_ORDER TO SHIPPER;

GRANT SELECT ON YUN.TAIXE TO SHIPPER;

GRANT SELECT ON YUN.TAIXE TO SHIPPER1;

GRANT SELECT, UPDATE (MA_KV_HD) ON YUN.TAIXE TO SHIPPER;

GRANT SELECT, UPDATE (MA_KV_HD) ON YUN.TAIXE TO SHIPPER1;


GRANT EXECUTE ON EMPLOYEE_GET_ORDER_DETAILS TO STAFF;

GRANT EXECUTE ON EMPLOYEE_GET_CONTRACTS TO STAFF;

grant select on YUN.nhanvien to staff;

grant select on YUN.hopdong to staff;




GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE TO admin1;

GRANT EXECUTE ON ADMIN_ADD_ADMIN_ACCOUNT TO ADMIN1;

GRANT EXECUTE ON ADMIN_REMOVE_ADMIN_ACCOUNT TO ADMIN1;

GRANT EXECUTE ON ADMIN_ADD_EMPLOYEE_ACCOUNT TO ADMIN1;

GRANT EXECUTE ON ADMIN_REMOVE_EMPLOYEE_ACCOUNT TO ADMIN1;

set serveroutput on;
--BEGIN YUN.PARTNER_UPDATE_PRODUCTS_DETAILS('SP01',N'Qu?n Jean', 'DT01', 'LH01', 200, 12); END;


GRANT EXECUTE ON PARTNER_ADD_PRODUCT TO PARTNER1;
--YUN.PARTNER_ADD_PRODUCT('SP10',N'Qu?n MLB', 'DT01', 'LH01', 200, 1000);

GRANT EXECUTE ON YUN.PARTNER_ADD_BRANCH TO PARTNER1;

GRANT EXECUTE ON PARTNER_ADD_PRODUCT_TO_BRANCH TO PARTNER1;

GRANT EXECUTE ON PARTNER_REMOVE_PRODUCT_FROM_BRANCH TO PARTNER1;

GRANT EXECUTE ON PARTNER_REMOVE_PRODUCT TO PARTNER1;

GRANT EXECUTE ON PARTNER_GET_ORDERS TO PARTNER1;

GRANT EXECUTE ON PARTNER_OR_DRIVER_UPDATE_DELIVERY_STATUS TO PARTNER1;

GRANT EXECUTE ON PARTNER_UPDATE_PRODUCTS_DETAILS TO PARTNER1;
--YUN.PARTNER_UPDATE_PRODUCTS_DETAILS('SP01',N'Qu?n Jean', 'DT01', 'LH01', 200, 430);
GRANT EXECUTE ON PARTNER_REGISTATION TO PARTNER1;

GRANT EXECUTE ON PARTNER_ADD_ORDER TO PARTNER1;

GRANT EXECUTE ON PARTNER_ORDER_TRACKING TO PARTNER1;

GRANT EXECUTE ON PARTNER_PRINT_ORDER TO PARTNER1;

GRANT EXECUTE ON PARTNER_REMOVE_ORDER TO PARTNER1;

GRANT EXECUTE ON PARTNER_PRINT_PRODUCTS_DETAILS TO PARTNER1;
--YUN.PARTNER_PRINT_PRODUCTS_DETAILS('SP01');

GRANT SELECT, UPDATE ON YUN.DONHANG TO PARTNER1;


